services:
  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "swordfish"
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./grafana/data:/var/lib/grafana:rw
      - ./grafana/etc:/etc/grafana
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/etc:/etc/prometheus:ro
      - ./prometheus/data:/prometheus:rw

  ping:
    image: czerwonk/ping_exporter
    command: ./ping_exporter --metrics.rttunit=s --metrics.deprecated=disable --config.path /config/config.yaml
    volumes:
      - ./ping_exporter:/config:ro
    ports:
      - "9427:9427"

  speedtest:
    image: miguelndecarvalho/speedtest-exporter
    ports:
      - "9798:9798"

