services:
  prometheus:
    image: prom/prometheus
    links:
      - ping
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/etc:/etc/prometheus:ro
      - ./prometheus/data:/prometheus:rw

  ping:
    image: czerwonk/ping_exporter
    command: ./ping_exporter --metrics.rttunit=s --metrics.deprecated=disable --config.path /config/config.yaml
    volumes:
      - ./ping_exporter:/config
    ports:
      - "9427:9427"

  speedtest:
    image: miguelndecarvalho/speedtest-exporter
    ports:
      - "9798:9798"

